version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: hris-frontend
    ports:
      - "3002:3002"
    environment:
      VITE_API_URL: ${VITE_API_URL}
