version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    container_name: hris-frontend
    ports:
      - "4002:4002"
    environment:
      VITE_API_URL: ${VITE_API_URL}
