"""add assignment_projects join table

Revision ID: 57dd2f2a5489
Revises: d64d124a32fa
Create Date: 2026-07-02 11:53:10.106752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57dd2f2a5489'
down_revision: Union[str, Sequence[str], None] = 'd64d124a32fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'project_id', name='uq_assignment_project')
    )
    op.create_index(op.f('ix_assignment_projects_id'), 'assignment_projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_projects_id'), table_name='assignment_projects')
    op.drop_table('assignment_projects')
    # ### end Alembic commands ###
