"""add tally-style vouchers cost centers tax rates reconciliation

Revision ID: 846307f846aa
Revises: 57dd2f2a5489
Create Date: 2026-07-02 16:20:09.471898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846307f846aa'
down_revision: Union[str, Sequence[str], None] = '57dd2f2a5489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('budget_amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_cost_centers_tenant_code')
    )
    op.create_index(op.f('ix_cost_centers_id'), 'cost_centers', ['id'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    op.create_table('bank_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('statement_balance', sa.Float(), nullable=False),
    sa.Column('book_balance', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reconciled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_reconciliations_id'), 'bank_reconciliations', ['id'], unique=False)
    op.add_column('journal_entries', sa.Column('voucher_type', sa.String(length=20), nullable=False, server_default='journal'))
    op.create_index('ix_journal_entries_tenant_voucher_type', 'journal_entries', ['tenant_id', 'voucher_type'], unique=False)
    op.add_column('journal_entry_lines', sa.Column('cost_center_id', sa.Integer(), nullable=True))
    op.add_column('journal_entry_lines', sa.Column('tax_rate_id', sa.Integer(), nullable=True))
    op.add_column('journal_entry_lines', sa.Column('is_reconciled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('journal_entry_lines', sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'journal_entry_lines', 'tax_rates', ['tax_rate_id'], ['id'])
    op.create_foreign_key(None, 'journal_entry_lines', 'cost_centers', ['cost_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entry_lines', type_='foreignkey')
    op.drop_constraint(None, 'journal_entry_lines', type_='foreignkey')
    op.drop_column('journal_entry_lines', 'reconciled_at')
    op.drop_column('journal_entry_lines', 'is_reconciled')
    op.drop_column('journal_entry_lines', 'tax_rate_id')
    op.drop_column('journal_entry_lines', 'cost_center_id')
    op.drop_index('ix_journal_entries_tenant_voucher_type', table_name='journal_entries')
    op.drop_column('journal_entries', 'voucher_type')
    op.drop_index(op.f('ix_bank_reconciliations_id'), table_name='bank_reconciliations')
    op.drop_table('bank_reconciliations')
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_cost_centers_id'), table_name='cost_centers')
    op.drop_table('cost_centers')
    # ### end Alembic commands ###
