"""add project progress and resource requests

Revision ID: 9d2e64c3bb12
Revises: 7ad52b3dc7cb
Create Date: 2026-07-01 12:08:47.363578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2e64c3bb12'
down_revision: Union[str, Sequence[str], None] = '7ad52b3dc7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_requests_id'), 'resource_requests', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.drop_constraint(op.f('assignments_employee_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_resource_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_project_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_tenant_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'resources', ['resource_id'], ['id'])
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.drop_constraint(op.f('attendances_tenant_id_fkey'), 'attendances', type_='foreignkey')
    op.drop_constraint(op.f('attendances_employee_id_fkey'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'attendances', 'employees', ['employee_id'], ['id'])
    op.create_index(op.f('ix_breaks_id'), 'breaks', ['id'], unique=False)
    op.drop_constraint(op.f('breaks_attendance_id_fkey'), 'breaks', type_='foreignkey')
    op.drop_constraint(op.f('breaks_tenant_id_fkey'), 'breaks', type_='foreignkey')
    op.create_foreign_key(None, 'breaks', 'attendances', ['attendance_id'], ['id'])
    op.create_foreign_key(None, 'breaks', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.drop_constraint(op.f('documents_employee_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'employees', ['employee_id'], ['id'])
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.drop_constraint(op.f('employees_tenant_id_fkey'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('employees_user_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.drop_constraint(op.f('leave_balances_employee_id_fkey'), 'leave_balances', type_='foreignkey')
    op.create_foreign_key(None, 'leave_balances', 'employees', ['employee_id'], ['id'])
    op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    op.drop_constraint(op.f('leave_types_tenant_id_fkey'), 'leave_types', type_='foreignkey')
    op.create_foreign_key(None, 'leave_types', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.drop_constraint(op.f('leaves_employee_id_fkey'), 'leaves', type_='foreignkey')
    op.drop_constraint(op.f('leaves_tenant_id_fkey'), 'leaves', type_='foreignkey')
    op.create_foreign_key(None, 'leaves', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leaves', 'tenants', ['tenant_id'], ['id'])
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('projects_tenant_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.drop_constraint(op.f('resources_tenant_id_fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_unique_constraint(None, 'tenants', ['name'])
    op.create_index(op.f('ix_timesheet_entries_id'), 'timesheet_entries', ['id'], unique=False)
    op.drop_constraint(op.f('timesheet_entries_timesheet_id_fkey'), 'timesheet_entries', type_='foreignkey')
    op.drop_constraint(op.f('timesheet_entries_tenant_id_fkey'), 'timesheet_entries', type_='foreignkey')
    op.create_foreign_key(None, 'timesheet_entries', 'timesheets', ['timesheet_id'], ['id'])
    op.create_foreign_key(None, 'timesheet_entries', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_timesheets_id'), 'timesheets', ['id'], unique=False)
    op.drop_constraint(op.f('timesheets_employee_id_fkey'), 'timesheets', type_='foreignkey')
    op.drop_constraint(op.f('timesheets_tenant_id_fkey'), 'timesheets', type_='foreignkey')
    op.create_foreign_key(None, 'timesheets', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'timesheets', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'timesheets', type_='foreignkey')
    op.drop_constraint(None, 'timesheets', type_='foreignkey')
    op.create_foreign_key(op.f('timesheets_tenant_id_fkey'), 'timesheets', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('timesheets_employee_id_fkey'), 'timesheets', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_timesheets_id'), table_name='timesheets')
    op.drop_constraint(None, 'timesheet_entries', type_='foreignkey')
    op.drop_constraint(None, 'timesheet_entries', type_='foreignkey')
    op.create_foreign_key(op.f('timesheet_entries_tenant_id_fkey'), 'timesheet_entries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('timesheet_entries_timesheet_id_fkey'), 'timesheet_entries', 'timesheets', ['timesheet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_timesheet_entries_id'), table_name='timesheet_entries')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_tenant_id_fkey'), 'resources', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_tenant_id_fkey'), 'projects', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'progress')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.create_foreign_key(op.f('leaves_tenant_id_fkey'), 'leaves', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('leaves_employee_id_fkey'), 'leaves', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_constraint(None, 'leave_types', type_='foreignkey')
    op.create_foreign_key(op.f('leave_types_tenant_id_fkey'), 'leave_types', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.create_foreign_key(op.f('leave_balances_employee_id_fkey'), 'leave_balances', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_user_id_fkey'), 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('employees_tenant_id_fkey'), 'employees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_employee_id_fkey'), 'documents', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_constraint(None, 'breaks', type_='foreignkey')
    op.drop_constraint(None, 'breaks', type_='foreignkey')
    op.create_foreign_key(op.f('breaks_tenant_id_fkey'), 'breaks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('breaks_attendance_id_fkey'), 'breaks', 'attendances', ['attendance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_breaks_id'), table_name='breaks')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_employee_id_fkey'), 'attendances', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('attendances_tenant_id_fkey'), 'attendances', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_tenant_id_fkey'), 'assignments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('assignments_project_id_fkey'), 'assignments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('assignments_resource_id_fkey'), 'assignments', 'resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('assignments_employee_id_fkey'), 'assignments', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_index(op.f('ix_resource_requests_id'), table_name='resource_requests')
    op.drop_table('resource_requests')
    # ### end Alembic commands ###
