"""add ledger groups

Revision ID: eb264d008f35
Revises: 82c521500038
Create Date: 2026-07-02 17:42:55.375480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb264d008f35'
down_revision: Union[str, Sequence[str], None] = '82c521500038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_groups.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_ledger_groups_tenant_code')
    )
    op.create_index(op.f('ix_ledger_groups_id'), 'ledger_groups', ['id'], unique=False)
    op.add_column('accounts', sa.Column('ledger_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'ledger_groups', ['ledger_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'ledger_group_id')
    op.drop_index(op.f('ix_ledger_groups_id'), table_name='ledger_groups')
    op.drop_table('ledger_groups')
    # ### end Alembic commands ###
